### ISSUE TITLE
NCCL failure common.cu:874 'unhandled system error'

### ISSUE THREAD

**Issue by ysdeal** [NVIDIA/nccl-tests#14]
I tested nccl-tests in nvidia-pytorch docker (downloaded from nvidia-cloud). The compiling went through. However, it failed when i tested "./build/all_reduce_perf -b 8 -e 128M -f 2 -g 8".
The error msg is 
"nThread 1 nGpus 8 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
NCCL failure common.cu:874 'unhandled system error'"

It seems that the problem caused by "NCCLCHECK(ncclGetUniqueId(&ncclId));"

Thanks for help.

**Comment by sjeaugey** [comment]
Hi,
Setting NCCL_DEBUG=WARN would make NCCL print a human-readable message of what is causing the error.

**Comment by ysdeal** [comment]
@sjeaugey Thanks. After setting NCCL_DEBUG, I got two additional messages:

e66aa18dc444:3171:3171 [0] misc/ibvwrap.cu:61 WARN Failed to open libibverbs.so[.1]
e66aa18dc444:3171:3171 [0] include/socket.h:311 WARN Socket creation failed : Address family not supported by protocol

Not sure what are the problems...

**Comment by ysdeal** [comment]
Solved by running the docker with --ipc=host option.

**Comment by sjeaugey** [comment]
NCCL displays that second WARN when it finds no usable IP interface (the first one is to be ignored unless you want to use Infiniband/RoCE).

I'm not sure why --ipc=host solved the problem.

**Comment by ysdeal** [comment]
@sjeaugey  Thanks a lot. You are right. It should be --net host that solved the problem.

**Comment by zxz-cc** [comment]
just add --ipc=host can solve this problem
