### ISSUE TITLE
Bus error when using 16 GPUs in one node

### ISSUE THREAD

**Issue by richardsliu** [NVIDIA/nccl-tests#143]
I am consistently seeing a crash when running the nccl-tests with 16 GPUs. This is the image I used:

```
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04 as builder

RUN apt-get update && apt-get install -y --no-install-recommends git curl gnupg
RUN git clone https://github.com/NVIDIA/nccl-tests.git 
WORKDIR /nccl-tests/
RUN make NCCL_HOME=/usr/lib/x86_64-linux-gnu

FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
COPY --from=builder /nccl-tests/build/all_reduce_perf /all_reduce_perf

CMD NCCL_DEBUG=INFO /all_reduce_perf -b 8 -e 128M -f 2 -g 16

```

Running this on a node with 16 Nvidia A100 40GB GPUs, I am seeing a Bus Error every time:

```
nccl-cuda118:27:55 [8] NCCL INFO Channel 19/0 : 8[80000] -> 7[b0] via P2P/direct pointer/read
nccl-cuda118:27:59 [12] NCCL INFO Channel 22/0 : 12[80040] -> 11[80030] via P2P/direct pointer/read
nccl-cuda118:27:50 [3] NCCL INFO Connected all trees
nccl-cuda118:27:50 [3] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
nccl-cuda118:27:60 [13] NCCL INFO Channel 12/0 : 13[80050] -> 12[80040] via P2P/direct pointer/read
nccl-cuda118:27:52 [5] NCCL INFO 24 coll channels, 32 p2p channels, 32 p2p channels per peer
Bus error (core dumped)
```

However if I drop the number of GPUs to 8, everything seems to work.

Any ideas why?

**Comment by sjeaugey** [comment]
Does it work with `-t 16`, or compiling the tests with MPI support and running one process per GPU?

**Comment by richardsliu** [comment]
So if I understand correctly, `-t` is the number of threads and `-g` is the number of GPUs per thread, so `t * g` should be at most 16.

I've tried `t * g < 16` and it works fine. If `t * g == 16`, the test fails with the error above. I've tried running the test with MPI across nodes, and I got this more detailed crash:

```
[nccl-launcher:00061] *** Process received signal ***
[nccl-worker-0:00017] *** Process received signal ***
[nccl-worker-0:00017] Signal: Bus error (7)
[nccl-worker-0:00017] Signal code: Non-existant physical address (2)
[nccl-worker-0:00017] Failing at address: 0x7fa6747ed000
[nccl-worker-0:00017] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7faa1d049420]
[nccl-worker-0:00017] [ 1] /lib/x86_64-linux-gnu/libc.so.6(+0x18bb41)[0x7faa1cc9bb41]
[nccl-worker-0:00017] [ 2] /lib/x86_64-linux-gnu/libnccl.so.2(+0x68d7c)[0x7faa1d0c0d7c]
[nccl-worker-0:00017] [ 3] /lib/x86_64-linux-gnu/libnccl.so.2(+0x5de3d)[0x7faa1d0b5e3d]
[nccl-worker-0:00017] [ 4] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7faa1d03d609]
[nccl-worker-0:00017] [ 5] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7faa1cc2f133]
[nccl-worker-0:00017] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 17 on node nccl-worker-0 exited on signal 7 (Bus error).
--------------------------------------------------------------------------
```

**Comment by sjeaugey** [comment]
Thanks. The next step would be to find out what the stack trace points to. Basically which functions are these:
```
[nccl-worker-0:00017] [ 2] /lib/x86_64-linux-gnu/libnccl.so.2(+0x68d7c)[0x7faa1d0c0d7c]
[nccl-worker-0:00017] [ 3] /lib/x86_64-linux-gnu/libnccl.so.2(+0x5de3d)[0x7faa1d0b5e3d]
```
Would you be able to generate a core file so that you can use gdb to get a backtrace with symbols? Alternatively, you could just run `gdb all_reduce_perf -b 8 -e 128M -f 2 -g 16`.

**Comment by richardsliu** [comment]
We ran this through gdb and got the following:

```
(gdb) info sharedlibrary
From                To                  Syms Read   Shared Object Library
0x00007ffff7fc5090  0x00007ffff7fee335  Yes (*)     /lib64/ld-linux-x86-64.so.2
0x00007ffff7c0f370  0x00007ffff7c7abba  Yes (*)     /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
0x00007ffff599edb0  0x00007ffff5aaf542  Yes         /lib/x86_64-linux-gnu/libnccl.so.2
0x00007ffff57d8440  0x00007ffff58dfb02  Yes (*)     /lib/x86_64-linux-gnu/libstdc++.so.6
0x00007ffff7edc3a0  0x00007ffff7f578e8  Yes (*)     /lib/x86_64-linux-gnu/libm.so.6
0x00007ffff5536700  0x00007ffff56c8abd  Yes (*)     /lib/x86_64-linux-gnu/libc.so.6
0x00007ffff7ec8040  0x00007ffff7ec8105  Yes (*)     /lib/x86_64-linux-gnu/libdl.so.2
0x00007ffff7ec3040  0x00007ffff7ec3105  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007ffff7ebe080  0x00007ffff7ebe275  Yes (*)     /lib/x86_64-linux-gnu/librt.so.1
0x00007ffff54f1660  0x00007ffff5507be5  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007ffff390cd80  0x00007ffff3d80fe4  Yes (*)     /usr/local/nvidia/lib64/libcuda.so.1
0x00007ffdc1013b40  0x00007ffdc111a182  Yes (*)     /usr/local/nvidia/lib64/libnvidia-ml.so.1
(*): Shared library is missing debugging information.
(gdb) bt
#0  0x00007ffff56bdbba in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff59d3f89 in memset (__len=4194656, __ch=0, __dest=0x7ffee433b000) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:59
#2  ncclShmSetup (create=1, ptr=<synthetic pointer>, fd=<synthetic pointer>, shmSize=4194656, shmPath=0x7ffd36ff68c0 "/dev/shm/nccl-EyDv2u") at misc/shmutils.cc:52
#3  ncclShmOpen (shmPath=shmPath@entry=0x7ffd36ff68c0 "/dev/shm/nccl-EyDv2u", shmSize=shmSize@entry=4194656, shmPtr=shmPtr@entry=0x7ffd36ff4ea0, devShmPtr=devShmPtr@entry=0x0, 
    create=create@entry=1) at misc/shmutils.cc:61
#4  0x00007ffff59c9ce6 in proxyProgressInit (comm=0x55556969f950) at proxy.cc:897
#5  proxyConnInit (comm=0x55556969f950, connectionPool=<synthetic pointer>, peer=0x7ffd36ff50c0) at proxy.cc:963
#6  ncclProxyService (_args=0x55556969f950) at proxy.cc:1105
#7  0x00007ffff55a2b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007ffff5634a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6


(gdb) info line *0x00007ffff59d3f89
Line 62 of "misc/shmutils.cc" starts at address 0x7ffff59d3f89 <_Z11ncclShmOpenPciPPvS1_i+217> and ends at 0x7ffff59d3f95 <_Z11ncclShmOpenPciPPvS1_i+229>.

```

**Comment by sjeaugey** [comment]
Ah. Maybe the size of /dev/shm is too small. If running inside the container, you may want to add `--shm-size=1g` to the container launch command line.

**Comment by richardsliu** [comment]
Thanks, I think that's the issue. I'm running the container on Kubernetes, so I needed to do something like this: https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614

**Comment by baymaxhuang** [comment]
I meet the same problem when I run nccl-tests on multiple nodes. In my case,  there are 36 nodes with nccl 2.18.3, and each node has 8 gpus and 8  ranks. The problem is finally resolved when I add --shm-size=1g to the container runtime.
