### ISSUE TITLE
MPIRun stuck on EC2

### ISSUE THREAD

**Issue by Luo-Liang** [NVIDIA/nccl-tests#16]
I'm seeing the same problem as otherson two Amazon EC2 p3.2xlarge instances with V100 GPU. Here is the command I have:

`mpirun -x LD_LIBRARY_PATH -x NCCL_SOCKET_IFNAME -np 2 -mca btl ^openib --hostfile hosts all_reduce_perf -b 1K -e 100M  -c 0`

where `hosts` are simply:

ip1 max_slots=1
ip2 max_slots=1

and NCCL_SOCKET_IFNAME=ens3

The symptom is what I see:
nThread 1 nGpus 1 minBytes 1024 maxBytes 104857600 step: 1048576(bytes) warmup iters: 5 iters: 20 validation: 0

Nothing else gets printed. Any ideas?

**Comment by sjeaugey** [comment]
Can you set NCCL_DEBUG=INFO and paste the output ? Thanks !

**Comment by Luo-Liang** [comment]
Hi! The following is all it printed out:

nThread 1 nGpus 1 minBytes 1024 maxBytes 104857600 step: 1048576(bytes) warmup iters: 5 iters: 20 validation: 0
INFO NCCL debug level set to INFO
INFO rank 0 using buffSize = 2097152
INFO rank 0 using device 0 (0000:00:1E.0)
INFO NCCL debug level set to INFO
INFO rank 1 using buffSize = 2097152
INFO rank 1 using device 0 (0000:00:1E.0)

I also did a gdb stacktrace, in case that helps:

Thread 5 (Thread 0x7f52d609f700 (LWP 2932)):
#0  0x00007f52de6846d9 in __GI___poll (fds=0x7f52a8000bd0, nfds=10, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f52d629f633 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007f52d630884d in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007f52d62a16a8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007f52de8f4164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f52de690def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f52d7a06700 (LWP 2931)):
#0  0x00007f52de69275f in accept4 (fd=22, addr=..., addr_len=0x7f52d7a05df8, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:32
#1  0x00007f52d62a057a in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007f52d6292abd in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007f52d62a16a8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007f52de8f4164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f52de690def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f52dd02b700 (LWP 2805)):
#0  0x00007f52de69110f in epoll_wait (epfd=10, events=0x55ee4d8ed960, maxevents=32, timeout=2100000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007f52dddd82c5 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#2  0x00007f52dddce114 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#3  0x00007f52dd0a8e2e in ?? () from /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_pmix_ext2x.so
#4  0x00007f52de8f4164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f52de690def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f52dd97c700 (LWP 2804)):
#0  0x00007f52de6846d9 in __GI___poll (fds=0x7f52d8000b20, nfds=1, timeout=3599114) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f52dddd76d3 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#2  0x00007f52dddce114 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#3  0x00007f52de43158e in ?? () from /usr/lib/x86_64-linux-gnu/libopen-pal.so.40
#4  0x00007f52de8f4164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f52de690def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f52dd98a740 (LWP 2798)):
#0  0x00007f52de6748d7 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007f52de914625 in ncclCommInitRank () from /usr/local/lib/libnccl.so.1
#2  0x000055ee4c861c30 in main ()

**Comment by Luo-Liang** [comment]
any comments on this?
Thanks!

**Comment by Luo-Liang** [comment]
I was indeed running with NCCL 1.x header

**Comment by YHRen** [comment]
Hi, @Luo-Liang 

I'm trying to run the nccl test on EC2 p3.x2large as well. But I have trouble to compile the nccl.
I'm using a ubuntu deep learning AMI, to compile nccl, I have to install nccl2 from deb, and then, compiling MPI (using the anaconda openmpi comes with the deep learning AMI, probably not a good idea). The compile throws an error. 

Could you please share your setups? for example, 
* what AMI did you use? 
* Did you install cuda, nccl, and mpi from scratch? 
* Did you use aws-ofi-nccl plug-in](https://github.com/aws/aws-ofi-nccl)

Thank you.

**Comment by AddyLaddy** [comment]
You may want to look at the build fixes in this PR for the AWS libfabric plugin; https://github.com/aws/aws-ofi-nccl/pull/11

**Comment by rashikakheria** [comment]
@YHRen You could use anaconda openmpi version for running `nccl-tests`. I have tried it in past and it works as expected. Regarding, how to install NCCL, you could use the instructions mentioned in NCCL github repository.

For deep learning AMI and to use `aws-ofi-nccl`, you would require to build libfabric, NCCL and aws-ofi-nccl from scratch.

**Comment by YHRen** [comment]
Hi @AddyLaddy  and @rashikakheria 

Thank you so much for your reply! 
Actually, I am using nvidia-docker containers on multiple EC2 hosts using docker overlay network to communicate.
Currently, there is no problem of running the code, by using the mca flags as @Luo-Liang used in this post. (Thank you!) 
So, there is actually no issue. 

But, I am wondering, will the "aws-ofi-nccl" library improve the communication performance? 
If so, should I install it in the docker container or in the host? 
(So sorry, I don't know how aws-ofi-nccl works, and this question must be very silly to you.)

Thank you so much.
Best wishes.

**Comment by rashikakheria** [comment]
`aws-ofi-nccl` plugin uses a different network provider which uses libfabric under the covers. You would install the plugin at same location where you have installed NCCL.
