### ISSUE TITLE
undefined reference to ncclRedOpDestroy

### ISSUE THREAD

**Issue by freshduer** [NVIDIA/nccl-tests#195]
i can compile the nccl-tests in cuda12 cuda11 environment 
but can not compile in cuda10.2 environment

my compile command is :
![image](https://github.com/NVIDIA/nccl-tests/assets/72605280/f0698c20-7443-4021-8006-5467f34672cc)
 
and error:
![image](https://github.com/NVIDIA/nccl-tests/assets/72605280/e66a2e3d-6274-4d56-94f7-3244a84233a8)

**Comment by freshduer** [comment]
after i link the native libnccl.so.2 to my compiled nccl ,error disappeared
![image](https://github.com/NVIDIA/nccl-tests/assets/72605280/9fa26d8d-c877-45a7-bfa6-d23ee6248f87)
so the NCCL_HOME does not funtion rightly?

**Comment by freshduer** [comment]
original libnccl is 2.6.3,so even if when i set the NCCL_HOME to my nccl 2.19.3，still not work
![image](https://github.com/NVIDIA/nccl-tests/assets/72605280/84a342a1-ccfe-44a6-b18c-e2bd909952e5)
