### ISSUE TITLE
Multinode NCCL 2.0 MPI Test code failure

### ISSUE THREAD

**Issue by mpatwary** [NVIDIA/nccl-tests#2]
I was trying this code using 2 nodes, each with 8 GPUs. The code ran well on single node, but when I tried two nodes, I am seeing the code either hangs or runs for infinite time. I tried three different cases as following, but were not successful.

1. mpirun -np 16 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 1 -c 0
>> nThread 1 nGpus 1 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
>> Cuda failure common.cu:891 'invalid device ordinal'

2. mpirun -np 2 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 8 -c 0
In this case, after printing the following line, the code hangs
>> nThread 1 nGpus 8 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0

3. mpirun -np 2 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 8 -g 1 -c 0
Same as Case 2, after printing the following line, the code hangs
>> nThread 8 nGpus 1 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0

I used SLURM to run the code using the following. In all the above cases, I set ntasks equals to np

>> #SBATCH --nodes=2
>> #SBATCH --ntasks=16
>> #SBATCH --gres=gpu:8

I set the following in the sbatch script.

>> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/xyz/nccl/build/lib/
>> export LD_LIBRARY_PATH=/home/xyz/openmpi-2.0.1-sm-gcc48-cuda-8.0-slurm-14.11.7/lib:/home/xyz/cuda-8.0.61/lib64:$LD_LIBRARY_PATH
>> export PATH=/home/xyz/openmpi-2.0.1-sm-gcc48-cuda-8.0-slurm-14.11.7/bin:/home/xyz/cuda-8.0.61/bin:$PATH

I used openmpi-2.0.1 and cuda-8.0.61 during compilation and run. NCCL 2.0 were used. Thanks for your help.

**Comment by AddyLaddy** [comment]
For the 'mpirun -np 16' test can you confirm that 8 processes per node are being launched. Maybe just run 'hostname' and see what is displayed.

**Comment by mpatwary** [comment]
Yes, I was running 8 process per node. Running mpirun -np 16 hostname show the following results.

node-73
node-73
node-73
node-73
node-73
node-73
node-73
node-73
node-79
node-79
node-79
node-79
node-79
node-79
node-79
node-79

But the following runs infinitely.

mpirun -np 16 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 1 -c 0

**Comment by AddyLaddy** [comment]
Ok thanks that looks correct. Can I also check that you used MPI=1 during the test compilation?

**Comment by mpatwary** [comment]
I use the below to compile:

>> make MPI=1 MPI_HOME=/home/xyz/openmpi-2.0.1-sm-gcc48-cuda-8.0-slurm-14.11.7 CUDA_HOME=/home/xyz/cuda-8.0.61 NCCL_HOME=/home/xyz/nccl/build

**Comment by sjeaugey** [comment]
'invalid device ordinal' indeed suggest that you are launching more MPI ranks than there are GPUs on a node. Your command line seems correct however, I don't see any obvious mistake. To help understand what is going wrong, it would be helpful to add a trace to print rank/localrank/gpuid before that line
: https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L643

As for the hangs, if the issue is not also a process rank/gpuid issue, it could be a network configuration problem. You may need to set NCCL_SOCKET_IFNAME to specify which network interface to use (http://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/index.html#ncclknobs).

If that doesn't solve the problem, I would suggest opening an issue on CUDA devzone.

**Comment by sjeaugey** [comment]
Actually, my bad, that would be before the call on line 891 (as the error reports) : https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L891

**Comment by mpatwary** [comment]
I solved the problem. Thanks @sjeaugey and @AddyLaddy for your help. The issue was mainly in my batch script. Somehow if I don't take the node using SBATCH exclusive, this was giving this problem.

**Comment by lucasleesw** [comment]
> I solved the problem. Thanks @sjeaugey and @AddyLaddy for your help. The issue was mainly in my batch script. Somehow if I don't take the node using SBATCH exclusive, this was giving this problem.

@mpatwary Excuse me, could you share the batch script solved this problem?
I met the same 'invalid device ordinal' error with SLURM.
Thank you!

**Comment by surak** [comment]
I have this error when I try more than 1 gpu per node. It seems that the common.h/CUDACHECK function gets confused when there's more than one gpu per hostname.
