### ISSUE TITLE
Test NCCL Hang

### ISSUE THREAD

**Issue by sdonoso** [NVIDIA/nccl-tests#244]
Hi, i have the next error when try the test:
There are two nodes with 8 A100 with the same config.

```
$ mpirun -np 2 -f hostfile -env UCX_NET_DEVICES=mlx5_0:1 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1
# nThread 1 nGpus 1 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid 398189 on    ranokau device  0 [0x07] NVIDIA A100-SXM4-80GB
#  Rank  1 Group  0 Pid  73214 on     lascar device  0 [0x07] NVIDIA A100-SXM4-80GB
ranokau:398189:398189 [0] NCCL INFO Bootstrap : Using enp45s0f0:146.155.155.83<0>
ranokau:398189:398189 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
ranokau:398189:398189 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
ranokau:398189:398189 [0] NCCL INFO NET/Plugin: Using internal network plugin.
lascar:73214:73214 [0] NCCL INFO cudaDriverVersion 12040
lascar:73214:73214 [0] NCCL INFO Bootstrap : Using enp45s0f0:146.155.155.84<0>
lascar:73214:73214 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
lascar:73214:73214 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
lascar:73214:73214 [0] NCCL INFO NET/Plugin: Using internal network plugin.
lascar:73214:73250 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_4:1/IB [3]mlx5_5:1/IB [4]mlx5_6:1/IB [5]mlx5_7:1/IB [6]mlx5_2:1/IB [RO]; OOB enp45s0f0:146.155.155.84<0>
lascar:73214:73250 [0] NCCL INFO Using non-device net plugin version 0
lascar:73214:73250 [0] NCCL INFO Using network IB
ranokau:398189:398189 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.21.5+cuda12.2
ranokau:398189:398281 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [4]mlx5_4:1/IB [5]mlx5_5:1/IB [6]mlx5_6:1/IB [7]mlx5_7:1/IB [RO]; OOB enp45s0f0:146.155.155.83<0>
ranokau:398189:398281 [0] NCCL INFO Using non-device net plugin version 0
ranokau:398189:398281 [0] NCCL INFO Using network IB
lascar:73214:73250 [0] NCCL INFO ncclCommInitRank comm 0x557fa5e72220 rank 1 nranks 2 cudaDev 0 nvmlDev 0 busId 7000 commId 0x8fe791c1f4993448 - Init START
ranokau:398189:398281 [0] NCCL INFO ncclCommInitRank comm 0x55dd0ef34390 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 7000 commId 0x8fe791c1f4993448 - Init START
lascar:73214:73250 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,00000000,00000000,ffffffff,ffffffff
ranokau:398189:398281 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,00000000,00000000,ffffffff,ffffffff
lascar:73214:73250 [0] NCCL INFO comm 0x557fa5e72220 rank 1 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
lascar:73214:73250 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
lascar:73214:73250 [0] NCCL INFO P2P Chunksize set to 131072
ranokau:398189:398281 [0] NCCL INFO comm 0x55dd0ef34390 rank 0 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
ranokau:398189:398281 [0] NCCL INFO Channel 00/02 :    0   1
ranokau:398189:398281 [0] NCCL INFO Channel 01/02 :    0   1
ranokau:398189:398281 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
ranokau:398189:398281 [0] NCCL INFO P2P Chunksize set to 131072
lascar:73214:73250 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [receive] via NET/IB/6/GDRDMA
lascar:73214:73250 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [receive] via NET/IB/6/GDRDMA
lascar:73214:73250 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [send] via NET/IB/6/GDRDMA
lascar:73214:73250 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [send] via NET/IB/6/GDRDMA
ranokau:398189:398281 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [receive] via NET/IB/1
ranokau:398189:398281 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [receive] via NET/IB/1
ranokau:398189:398281 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [send] via NET/IB/1
ranokau:398189:398281 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [send] via NET/IB/1
ranokau:398189:398281 [0] NCCL INFO Connected all rings
ranokau:398189:398281 [0] NCCL INFO Connected all trees
ranokau:398189:398281 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
ranokau:398189:398281 [0] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
lascar:73214:73250 [0] NCCL INFO Connected all rings
lascar:73214:73250 [0] NCCL INFO Connected all trees
lascar:73214:73250 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
lascar:73214:73250 [0] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
lascar:73214:73250 [0] NCCL INFO TUNER/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
lascar:73214:73250 [0] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
lascar:73214:73250 [0] NCCL INFO ncclCommInitRank comm 0x557fa5e72220 rank 1 nranks 2 cudaDev 0 nvmlDev 0 busId 7000 commId 0x8fe791c1f4993448 - Init COMPLETE
ranokau:398189:398281 [0] NCCL INFO TUNER/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
ranokau:398189:398281 [0] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
ranokau:398189:398281 [0] NCCL INFO ncclCommInitRank comm 0x55dd0ef34390 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 7000 commId 0x8fe791c1f4993448 - Init COMPLETE
#
#                                                              out-of-place                       in-place          
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       

lascar:73214:73257 [0] transport/net_ib.cc:101 NCCL WARN NET/IB : mlx5_2:1 Got async event : local catastrophic error

lascar:73214:73257 [0] transport/net_ib.cc:101 NCCL WARN NET/IB : mlx5_2:1 Got async event : local catastrophic error

ranokau:398189:398314 [0] transport/net_ib.cc:1909 NCCL WARN NET/IB : Got completion from peer 146.155.155.84<42751> with status=12 opcode=0 len=32517 vendor err 129 (Send)
ranokau:398189:398314 [0] NCCL INFO transport/net.cc:1137 -> 6
ranokau:398189:398314 [0] NCCL INFO proxy.cc:698 -> 6
ranokau:398189:398314 [0] NCCL INFO proxy.cc:878 -> 6 [Progress Thread]

ranokau:398189:398314 [0] transport/net_ib.cc:1909 NCCL WARN NET/IB : Got completion from peer 146.155.155.84<47843> with status=12 opcode=32517 len=32517 vendor err 129 (Send)
ranokau:398189:398314 [0] NCCL INFO transport/net.cc:1137 -> 6
ranokau:398189:398314 [0] NCCL INFO proxy.cc:698 -> 6
ranokau:398189:398314 [0] NCCL INFO proxy.cc:878 -> 6 [Progress Thread]
ranokau:398189:398312 [0] NCCL INFO [Service thread] Connection closed by localRank 0
ranokau:398189:398189 [0] NCCL INFO comm 0x55dd0ef34390 rank 0 nranks 2 cudaDev 0 busId 7000 - Abort COMPLETE
ranokau: Test NCCL failure common.cu:306 'remote process exited or there was a network error / '
 .. ranokau pid 398189: Test failure common.cu:404
 .. ranokau pid 398189: Test failure common.cu:591
 .. ranokau pid 398189: Test failure all_reduce.cu:90
 .. ranokau pid 398189: Test failure common.cu:618
 .. ranokau pid 398189: Test failure common.cu:1063
 .. ranokau pid 398189: Test failure common.cu:876
```
**mpirun --version**
```
HYDRA build details:
    Version:                                 4.2.1
    Release Date:                            Wed Apr 17 15:30:02 CDT 2024
    CC:                              gcc      
    Configure options:                       '--disable-option-checking' '--prefix=/usr/local/mpich' '--with-hwloc=embedded' '--with-cuda=/usr/local/cuda' '--with-device=ch4:ucx' '--cache-file=/dev/null' '--srcdir=../../../../src/pm/hydra' 'CC=gcc' 'CFLAGS= -O2' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= -DNETMOD_INLINE=__netmod_inline_ucx__ -I/usr/local/cuda/include -I/home/sdonoso/mpich-4.2.1/build/src/mpl/include -I/home/sdonoso/mpich-4.2.1/src/mpl/include -I/home/sdonoso/mpich-4.2.1/modules/json-c -I/home/sdonoso/mpich-4.2.1/build/modules/json-c -I/home/sdonoso/mpich-4.2.1/modules/hwloc/include -I/home/sdonoso/mpich-4.2.1/build/modules/hwloc/include -D_REENTRANT -I/home/sdonoso/mpich-4.2.1/build/src/mpi/romio/include -I/home/sdonoso/mpich-4.2.1/src/pmi/include -I/home/sdonoso/mpich-4.2.1/build/src/pmi/include -I/home/sdonoso/mpich-4.2.1/build/modules/yaksa/src/frontend/include -I/home/sdonoso/mpich-4.2.1/modules/yaksa/src/frontend/include'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select
```
The enviroment for the two nodes:
```
OS:Ubuntu 22.04


MLNX_OFED_LINUX-24.04-0.7.0.0


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```

**Comment by kiskra-nvidia** [comment]
It seems like the network configuration on the two nodes is not the same:

```
lascar:73214:73250 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_4:1/IB [3]mlx5_5:1/IB [4]mlx5_6:1/IB [5]mlx5_7:1/IB [6]mlx5_2:1/IB [RO]; OOB enp45s0f0:146.155.155.84<0>
ranokau:398189:398281 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [4]mlx5_4:1/IB [5]mlx5_5:1/IB [6]mlx5_6:1/IB [7]mlx5_7:1/IB [RO]; OOB enp45s0f0:146.155.155.83<0>
```

Is that intentional? Can you try limiting NCCL to a subset of NICs using `NCCL_IB_HCA` (see [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-ib-hca))?

**Comment by sdonoso** [comment]
thanks, that solved it, apparently there are two cards wrongly connected in one of the servers.
