### ISSUE TITLE
Running NCCL test on multiple nodes

### ISSUE THREAD

**Issue by leeQT** [NVIDIA/nccl-tests#27]
Hi, I'm trying to building NCCL benchmark and I want to run some tests on multiple nodes but the present tests don't seem to support that. How can I change it?

**Comment by sjeaugey** [comment]
Did you try compiling them with MPI=1 ?
```
make MPI=1 MPI_HOME=/path/to/mpi CUDA_HOME=/path/to/cuda NCCL_HOME=/path/to/nccl
mpirun -H host1,host2 -np 2 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
```

**Comment by leeQT** [comment]
> Did you try compiling them with MPI=1 ?
> 
> ```
> make MPI=1 MPI_HOME=/path/to/mpi CUDA_HOME=/path/to/cuda NCCL_HOME=/path/to/nccl
> mpirun -H host1,host2 -np 2 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
> ```

I tried this but it seems that this command just ran all_reduce_perf on two host seperatly and there wasn't communication between nodes?

Here's my command:
`mpirun -H 10.251.154.148,10.251.154.143 -np 2 ./all_reduce_perf -b 8 -e 128M -f 128 -g 2`
(They are two nodes and each of them has 2 GPUs)
and part of the output:
`# Out of bounds values : 0 OK
# Avg bus bandwidth    : 3.94145 
#
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 3.94156 `

And if I run it on single node, the average bus bandwidth is the same.
command:
`mpirun -H 10.251.154.148 ./all_reduce_perf -b 8 -e 128M -f 128 -g 2`
result:
`# Out of bounds values : 0 OK
# Avg bus bandwidth    : 3.95192`

**Comment by kwen2501** [comment]
You would probably need to clean the previous build first via `make clean` before building again with MPI.

**Comment by leeQT** [comment]
> You would probably need to clean the previous build first via `make clean` before building again with MPI.

Thanks this solved my problem.

**Comment by wanzaiqidao** [comment]
> You would probably need to clean the previous build first via `make clean` before building again with MPI.

it helps me a lot. thank you
