### ISSUE TITLE
Test CUDA failure common.cu:730 'no CUDA-capable device is detected'

### ISSUE THREAD

**Issue by shuxiaobo** [NVIDIA/nccl-tests#30]
I run the test after install nccl from rpm
> sudo yum install libnccl-2.4.8-1+cuda10.0 libnccl-devel-2.4.8-1+cuda10.0 libnccl-static-2.4.8-
1+cuda10.0

The error does not show any mean I understand.

> nThread 1 nGpus 8 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
> Using devices
458398: Test CUDA failure common.cu:730 'no CUDA-capable device is detected'

The machine I run contain 8 Tesla T4

Could you help me solve this?

**Comment by sjeaugey** [comment]
Does the tests run fine with just 2 GPUs (`-g 2` or -`t 2`) ? How many GPUs does `nvidia-smi` report ?

**Comment by xutianming** [comment]
I met the same problem. In my case, I reinstalled cuda and it works.

**Comment by AddyLaddy** [comment]
Closing old issues. Please open another one if you are still seeing issues.
