### ISSUE TITLE
make error `error: missing binary operator before token "("`

### ISSUE THREAD

**Issue by zsef123** [NVIDIA/nccl-tests#35]
```
user in nccl-tests at ubuntu on  master
➜ make
make -C src build
make[1]: Entering directory '/home/user/nccl-tests/src'
Compiling  all_reduce.cu                       > ../build/all_reduce.o
Compiling  common.cu                           > ../build/common.o
common.cu:335:38: error: missing binary operator before token "("
 #if NCCL_VERSION_CODE >= NCCL_VERSION(2,4,0)
                                      ^
Makefile:72: recipe for target '../build/common.o' failed
make[1]: *** [../build/common.o] Error 1
make[1]: Leaving directory '/home/user/nccl-tests/src'
Makefile:17: recipe for target 'src.build' failed
make: *** [src.build] Error 2
```
This error occurs when I build

Env : 
```
user in ~ at ubuntu
➜ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
```
user in ~ at ubuntu
➜ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sjeaugey** [comment]
Humm.. could it be you are trying to compile the NCCL tests against a very old NCCL 1.x ?

**Comment by HeyangQin** [comment]
According to `apt` I have nccl  2.8.3 yet I still have this issue...
```
(base) (heyangq)heyangq@node10:~/nccl-tests$ apt search nccl
Sorting... Done
Full Text Search... Done
libhttpasyncclient-java/xenial 4.1-1 all
  HTTP/1.1 compliant asynchronous HTTP agent implementation

libnccl-dev/unknown,now 2.8.3-1+cuda11.0 amd64 [installed]
  NVIDIA Collective Communication Library (NCCL) Development Files

libnccl1/unknown 1.2.3-1+cuda8.0 amd64
  NVIDIA Communication Collectives Library (NCCL) Runtime

libnccl2/unknown,now 2.8.3-1+cuda11.0 amd64 [installed,automatic]
  NVIDIA Collective Communication Library (NCCL) Runtime

libvncclient1/xenial-updates,xenial-security 0.9.10+dfsg-3ubuntu0.16.04.6 amd64
  API to write one's own VNC server - client library

libvncclient1-dbg/xenial-updates,xenial-security 0.9.10+dfsg-3ubuntu0.16.04.6 amd64
  debugging symbols for libvncclient

python-ncclient/xenial 0.4.7-1 all
  Python library for NETCONF clients

texlive-latex-extra/xenial 2015.20160320-1 all
  TeX Live: LaTeX additional packages

xvnc4viewer/xenial 4.1.1+xorg4.3.0-37.3ubuntu2 amd64
  Virtual network computing client software for X


```

**Comment by sjeaugey** [comment]
The most probable reason is that you still have some NCCL 1.x include somewhere (like in `/usr/local/include`, or somewhere else) which is picked up by your compilation.

**Comment by HeyangQin** [comment]
> The most probable reason is that you still have some NCCL 1.x include somewhere (like in `/usr/local/include`, or somewhere else) which is picked up by your compilation.

Thanks for the prompt reply. You are right. There is an ancient `nccl.h` in my `/usr/local/include`. After removing it and reinstall `libnccl-dev` the problem is gone!
