### ISSUE TITLE
./build/all_reduce_perf: error while loading shared libraries: libnccl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ShreyasKudari** [NVIDIA/nccl-tests#85]
There was no issue in building the tests (without MPI) but running the quick example gives the above error. I built and installed NCCL from the repo and am running this on a compute node on [Longhorn](https://portal.tacc.utexas.edu/user-guides/longhorn#files) at TACC. 
The command I used to build the tests:
`make CUDA_HOME=/usr/local/cuda-10.2 NCCL_HOME=$SCRATCH/nccl/build`
The command I used to run the tests:
`./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4`

**Comment by AddyLaddy** [comment]
Have you also set `LD_LIBRARY_PATH=$SCRATCH/nccl/build/lib:$LD_LIBRARY_PATH`  ?

**Comment by ShreyasKudari** [comment]
No I just added that and it works. Thank you
