### ISSUE TITLE
Performance degrades drastically between two docker in one host

### ISSUE THREAD

**Issue by cookie-YL** [NVIDIA/nccl-tests#93]
Environment:
Docker using host network 
ubuntu 20.04 LTS with CUDA 11.4 Driver 450.102.04 NCCL 2.10.3 
Tesla V100 SXM2 32GB

Host GPU topo -m
	GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity
GPU0	 X 	NV1	NV2	NV1	0-71	0-1
GPU1	NV1	 X 	NV1	NV2	0-71	0-1
GPU2	NV2	NV1	 X 	NV2	0-71	0-1
GPU3	NV1	NV2	NV2	 X 	0-71	0-1

Dear contributor:
Now I create two docker with each holding two graphic cards, 01 and 23 respectively. When I NCCL_test all_reduce between two docker using: 
`NCCL_DEBUG=info horovodrun -np 4 -H node1:2,node2:2 ./build/all_reduce_perf -b 18M -e 600M -f 2 -g 2` 
the output shows the first completed avg bus bandwidth is 15.5071

But if I run nccl_test with one docker holding four cards with 
`NCCL_DEBUG=info horovodrun -np 4 -H node3:4 ./build/all_reduce_perf -b 18M -e 600M -f 2 -g 4`
the first completed avg bus bandwidth reaches 31.73 and even higher.

I check the info printed by NCCL, the channels are all via P2P/direct pointer, so why there is a huge downgrade when using two dockers in the circumstance that I've already run in host network ?

Plus, when I use sar and ethstatus to monitor the network traffic in lo and eth0, neither of them shows any traffic when nccl-testing, how can I catch the traffic of it ?

Thanks for your reply ~

**Comment by sjeaugey** [comment]
When run in different docker instances, NCCL may not be able to properly detect the NVLinks going to other docker images because it cannot see those other GPUs from the container.

So you could end up with a single, simple ring, instead of multiple rings using all NVLinks in the most optimal way. Can you provide the log in both cases setting NCCL_DEBUG=INFO? That would probably tell us why there is such a performance difference.

**Comment by cookie-YL** [comment]
Sure, this is the node1 and node2 with two cards separately log:  [https://pastebin.ubuntu.com/p/BvxBRCwnGh/](https://pastebin.ubuntu.com/p/BvxBRCwnGh/)
this is the node3 with four cards log: [https://pastebin.ubuntu.com/p/BvxBRCwnGh/](https://paste.ubuntu.com/p/nyfy8YjfYq/)

**Comment by cookie-YL** [comment]
oh, I suddenly realize that I might execute a wrong command, in `NCCL_DEBUG=info horovodrun -np 4 -H node1:2,node2:2 ./build/all_reduce_perf -b 18M -e 600M -f 2 -g 2`, I launch 2 processes in each docker with 1 thread in each process and **2** gpus per thread, which means the total rank of each docker is two times of real rank(4=2*2), I guess it might cause huge pressure on each gpu and thus result in performance influence. I retry `NCCL_NTHREADS=512 NCCL_DEBUG=info horovodrun -np 2 -H node1:1,node4:1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 1 -t 2` and `NCCL_NTHREADS=512 NCCL_DEBUG=info horovodrun -np 2 -H node1:1,node4:1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 2` and both get ~44 avg bus bandwidth. I think it is much closer to the real performance.

**Comment by cookie-YL** [comment]
Now with the rectified command, the situation turns out that:
* on 1 docker with four cards running command: `NCCL_DEBUG=info horovodrun -np 1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 4` and `NCCL_DEBUG=info horovodrun -np 1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 1 -t 4` both can get 82.4985
* on 2 dockers with two cards separately running command: `NCCL_DEBUG=info horovodrun -np 2 -H node1:1,node4:1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 1 -t 2` and `NCCL_DEBUG=info horovodrun -np 2 -H node1:1,node4:1 ./build/all_reduce_perf -b 32M -e 512M -f 2 -g 2` both can get 44.78

Is this result correct ?

**Comment by sjeaugey** [comment]
Now I'm confused. I thought this was a single perf test, but I realize you are overloading GPUs with multiple NCCL ranks which is not guaranteed to work.

What would make sense to me would be to compile NCCL perf tests with `MPI=1` so that your horovodrun launches a single job, then never use `-t` nor `-g` so that we launch one process per GPU.

**Comment by cookie-YL** [comment]
The more I test, the more confused I am now 😂 so go back to the beginning, I want to figure out two questions:
1. what is the command which can mock/measure the all_reduce communication in ML Training routine between node1 and node2 with 2 cards separately. 
2. Is there any tutorials about how to comprehend the trees constructed in NCCL_DEBUG=info, e.g. NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
Thanks for your patience 👍

**Comment by sjeaugey** [comment]
I would go back to the original command line and launch them again without `-t` or `-g`.
Two nodes x 2 GPUs:
```
NCCL_DEBUG=info horovodrun -np 4 -H node1:2,node2:2 ./build/all_reduce_perf -b 18M -e 600M -f 2
```
And one node x 4 GPUs:
```
NCCL_DEBUG=info horovodrun -np 4 -H node3:4 ./build/all_reduce_perf -b 18M -e 600M -f 2
```
For this to work, you need the NCCL perf tests to be compiled with `make MPI=1 [other make options]`

**Comment by cookie-YL** [comment]
After compiling with MPI=1 option and run without -g and -t, the first Two nodes x2 GPUs uses "via NET/socket/#num",  the bus bandwidth degrades to 3.3GB/s which I think is the iperf rate of eth0 socket. 
BTW, after compiling like this, horovodrun can not be used, the error is "BTLs attempted: self smcuda vader" so I switch to mpirun, I hope this would not affect.

**Comment by cookie-YL** [comment]
I've confirmed that it is the using of NET/Socket instead of P2P/IPC between two docker affects the performance of my ML Distributed Training, so how can I use the P2P/IPC communication in force between two dockers ?

**Comment by sjeaugey** [comment]
Ok, now it makes sense. I'm not sure why horovodrun would restrict MPI to only intra-node BTLs and not inter-node ones. Using mpirun is fine as well.

IPCs do not work between containers (See https://github.com/NVIDIA/nccl/issues/324#issuecomment-615357976) unless all gpus are visible from each container. So you need to run every container with all the GPUs to allow NCCL to properly discover NVLinks and use IPCs.

**Comment by cookie-YL** [comment]
It solves my puzzle, many thanks~
